name: CI pipeline
run-name: ${{ github.actor }} is executing CI. 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run security checks
        run: |
          chmod +x security.sh
          ./security.sh
      - name: Run tests and coverage
        run: |
          chmod +x tests.sh
          ./tests.sh
      - name: Snyk scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        