name: CI pipeline
run-name: ${{ github.actor }} is executing CI. 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          set -e
          pip install -r requirements.txt
      
      - name: Run flake8
        run: |
          set -e
          flake8

      - name: Run tests and coverage
        run: |
          set -e
          chmod +x ./tests.sh
          ./tests.sh
  
      - name: Safety and Bandit
        run: |
          set -e
          chmod +x ./security.sh
          ./security.sh

      - name: Snyk 
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      
      - name: build docker compose
        run: |
          set -e
          docker-compose -f docker-compose.yaml build
        
       
      
