name: CI pipeline
run-name: ${{ github.actor }} is executing CI. 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run flake8
        run: flake8

      - name: Run tests and coverage
        run: |
          chmod +x tests.sh
          ./tests.sh
  
      - name: Run security checks
        run: |
          chmod +x security.sh
          ./security.sh

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Initialize SonarQube
        id: sonarqube_token
        run: |
          wget -O $HOME/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x $HOME/wait-for-it.sh
          $HOME/wait-for-it.sh sonarqube:9000 -t 0 -- echo "SonarQube is operational"
          SONAR_TOKEN=$(curl -u ${{ secrets.SONARQUBE_USER }}:${{ secrets.SONARQUBE_PASSWORD }} -X POST "http://sonarqube:9000/api/authentication/login" | jq -r .token)
          curl -u ${{ secrets.SONARQUBE_USER }}:${{ secrets.SONARQUBE_PASSWORD }} -X POST "http://sonarqube:9000/api/projects/create?name=my_project_name&project=my_project_key"
          SONAR_PROJECT_TOKEN=$(curl -u ${{ secrets.SONARQUBE_USER }}:${{ secrets.SONARQUBE_PASSWORD }} -X POST "http://sonarqube:9000/api/user_tokens/generate?name=my_project_key" | jq -r .token)
          echo "SONAR_PROJECT_TOKEN=$SONAR_PROJECT_TOKEN" >> $GITHUB_ENV

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env: 
          SONAR_TOKEN: ${{ env.SONAR_PROJECT_TOKEN }}
          SONAR_HOST_URL: http://sonarqube:9000
